name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Start database container
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: './docker-compose.yml'  # путь к вашему docker-compose

    - name: Waiting for container start
      run: sleep 30

    - name: Start SUT
      run: java -jar ./artifacts/app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/db &

    - name: Run tests with Gradle
      run: ./gradlew test -Dselenide.headless=true --info
